export const audioList = [
    { id: 1, title: '001 Misbahir Rawi', url: require('../assets/audio/001.mp3') },
    // { id: 2, title: '002 Misbahir Rawi', url: require('../assets/audio/002.mp3') },
    // { id: 3, title: '003 Misbahir Rawi', url: require('../assets/audio/003.mp3') },
    // { id: 4, title: '004 Misbahir Rawi', url: require('../assets/audio/004.mp3') },
    // { id: 5, title: '005 Misbahir Rawi', url: require('../assets/audio/005.mp3') },
    // { id: 6, title: '006 Misbahir Rawi', url: require('../assets/audio/006.mp3') },
    // { id: 7, title: '007 Misbahir Rawi', url: require('../assets/audio/007.mp3') },
    // { id: 8, title: '008 Misbahir Rawi', url: require('../assets/audio/008.mp3') },
    // { id: 9, title: '009 Misbahir Rawi', url: require('../assets/audio/009.mp3') },
    // { id: 11, title: '011 Misbahir Rawi', url: require('../assets/audio/011.mp3') },
    // { id: 12, title: '012 Misbahir Rawi', url: require('../assets/audio/012.mp3') },
    // { id: 13, title: '013 Misbahir Rawi', url: require('../assets/audio/013.mp3') },
    // { id: 14, title: '014 Misbahir Rawi', url: require('../assets/audio/014.mp3') },
    // { id: 15, title: '015 Misbahir Rawi', url: require('../assets/audio/015.mp3') },
    // { id: 16, title: '016 Misbahir Rawi', url: require('../assets/audio/016.mp3') },
    // { id: 17, title: '017 Misbahir Rawi', url: require('../assets/audio/017.mp3') },
    // { id: 18, title: '018 Misbahir Rawi', url: require('../assets/audio/018.mp3') },
    // { id: 19, title: '019 Misbahir Rawi', url: require('../assets/audio/019.mp3') },
  ];
  